name: Release
on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            rust \
            gtk4 \
            gtk4-layer-shell \
            pkg-config \
            base-devel

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/twinkl
          generate_release_notes: true
